// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	users "github.com/amdrx480/go-lms/businesses/users"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetByEmail provides a mock function with given fields: ctx, userDomain
func (_m *Repository) GetByEmail(ctx context.Context, userDomain *users.Domain) (users.Domain, error) {
	ret := _m.Called(ctx, userDomain)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 users.Domain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *users.Domain) (users.Domain, error)); ok {
		return rf(ctx, userDomain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *users.Domain) users.Domain); ok {
		r0 = rf(ctx, userDomain)
	} else {
		r0 = ret.Get(0).(users.Domain)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *users.Domain) error); ok {
		r1 = rf(ctx, userDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserProfile provides a mock function with given fields: ctx
func (_m *Repository) GetUserProfile(ctx context.Context) (users.Domain, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfile")
	}

	var r0 users.Domain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (users.Domain, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) users.Domain); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(users.Domain)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, userDomain
func (_m *Repository) Register(ctx context.Context, userDomain *users.Domain) (users.Domain, error) {
	ret := _m.Called(ctx, userDomain)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 users.Domain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *users.Domain) (users.Domain, error)); ok {
		return rf(ctx, userDomain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *users.Domain) users.Domain); ok {
		r0 = rf(ctx, userDomain)
	} else {
		r0 = ret.Get(0).(users.Domain)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *users.Domain) error); ok {
		r1 = rf(ctx, userDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
